### ISSUE TITLE
hl-updated-cmake building linker errors

### ISSUE THREAD

**Issue by thenewkgb** [SamVanheer/halflife-unified-sdk#410]
I have ran `cmake ..` and `cmake --build . --config=Release` with your cmake repo, building with VS2022 Build Tools on a laptop. It finds Thread it finds OpenGL. It starts smoothly with a couple of warnings, but then spews a lot of linker errors - `unresolved external symbol`. In build/src/game/client I only see .exp and .lib files. In game/server I do see hl.dll.

**Comment by SamVanheer** [comment]
Half-Life Updated CMake is archived, you shouldn't use that.

You're getting that error because you didn't set the install prefix to your mod directory. The build instructions for the Unified SDK explain this part: https://github.com/SamVanheer/halflife-unified-sdk/blob/9ce8dbc3643e269f463e7c5e85943be4203290b9/BUILDING.md

But note that Half-Life Updated CMake does not have many of the updates made to this project's configuration so that tutorial isn't accurate for the most part.

**Comment by thenewkgb** [comment]
Many thanks for replying.

I did see halflife-unified is WIP so I had to choose an older version to use or reference from. I did try to compile the original repo with C++98 requirements, but it needed more C++ knowledge than I have currently.

Also I saw to post issues in this repo as all the older projects are not supported any more. I'll try to add a mod prefix and see how it goes.

**Comment by thenewkgb** [comment]
Well thanks for the help, but I would assume no more support can be shared with me (as the project is archived and people are busy). I will however use it for reference. Thanks again.

**Comment by SamVanheer** [comment]
These projects are in a bit of flux right now. Once Unified SDK V1.0.0 is out it should be stable to use for CMake-based mod development. Hopefully it shouldn't take too much time to get that release out.
