### ISSUE TITLE
Wrong beam outer color in test chamber control room.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#433]
In map `c1a0c`, the player must pass by the control room in which it must avoid a laser beam. The Unified SDK's outer beam color appears red while it's green in the current Steam release.

Current HL1 Steam release:

![image](https://user-images.githubusercontent.com/12233175/210459469-ba925e88-e60f-4f42-9999-a99b4d8a1ebc.png)

Unified SDK:

![image](https://user-images.githubusercontent.com/12233175/210459508-bb64d21e-4b55-4d4c-b957-5b724701deb3.png)

**Steps to reproduce**

1. Open the console and type the following:

   ```
   sv_cheats 1
   map c1a0c
   noclip
   ```

2. Go to the control room and trigger the beam
3. The beam's outer color should be red (incorrect)

**In-game version**

```
Build type: Release
Release type: Pre-Alpha
Client:
  Version 1.0.0
  Branch: master
  Tag: CI build
  Commit Hash: f47c2f6a405aa33b386b63188067e1853484687e
Server:
  Version 1.0.0
  Branch: master
  Tag: CI build
  Commit Hash: f47c2f6a405aa33b386b63188067e1853484687e

WIP build not suited for use (testing only)
```

**Comment by SamVanheer** [comment]
This happens because the vector parsing function was rewritten to use a stricter parser. The original parser parses out floating point values and then skips everything until it reaches whitespace. The new one parses out the number and then parses the next non-whitespace character after that.

In this map's case the rendercolor keyvalue uses the wrong format: `180, 255, 96` instead of `180 255 96` so parsing fails.
