### ISSUE TITLE
(of1a3, of1a4) Elevator does not play move sound after level transition.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#513]
**Description**

See https://github.com/ValveSoftware/halflife/issues/3366

**Build** : [Half-Life Unified SDK V1.0.0 Release Candidate 001](https://github.com/SamVanheer/halflife-unified-sdk/releases/tag/UNIFIED-V1.0.0-RC001)

**Project info**

Using `cl_projectinfo_print_all` :

```
Project info for client:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:02:58 Jul 30 2023
Project info for server:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:03:54 Jul 30 2023
```

**Comment by SamVanheer** [comment]
This is a limitation of the save game system and the engine in general. The entity is transitioned in a moving state but the save system doesn't save the client-side sound state and can't restore it.

Restarting the sound can't be done either because players don't exist yet when the entity is restored and restoring that could cause other problems if a lot of entities restart sounds.
