### ISSUE TITLE
Gauss gun continues to play spin animation even after forced fire occurred.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#529]
**Description**

See https://github.com/ValveSoftware/halflife/issues/3386

**Build** : [Half-Life Unified SDK V1.0.0 Release Candidate 001](https://github.com/SamVanheer/halflife-unified-sdk/releases/tag/UNIFIED-V1.0.0-RC001)

**Project info**

Using `cl_projectinfo_print_all` :

```
Project info for client:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:02:58 Jul 30 2023
Project info for server:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:03:54 Jul 30 2023
```

**Comment by SamVanheer** [comment]
This happens because `m_fInAttack` is reset to **0** by the server when it runs the frame. The client then runs it, sees it's **0** and doesn't run the attack logic which plays the animation.

I tried to work around the issue but it doesn't look like it can be done easily. Workarounds are likely to introduce other bugs in the process so i'm leaving this as-is.
